
#.
#World
[World]
	#.
	#Chance for and Ore Stone to spawn when on top of Bedrock while Milkshake Stone Generating
	#Range: 1 ~ 100
	chanceForOreStone = 25
	#.
	#Chance for and Ore Stone to spawn when on top of Artificial Bedrock while Milkshake Stone Generating
	#Range: 0 ~ 100
	chanceForArtificialOreStone = 5

#.
#Packmakers' control panel for internal recipe compat
[recipes]
	#.
	#.
	#Allow the Hydraulic Press to process entire stacks at a time.
	hydraulicBulkPressing = true
	#.
	#Value Hydraulic Press to drain amount of lava of each bonk.
	#Range: 1 ~ 1000
	hydraulicLavaDrainPressing = 250
	#.
	#Value Hydraulic Press to drain amount of fluid of each bonk.
	#Range: 1 ~ 1000
	hydraulicFluidDrainPressing = 1000
	#.
	#Refined Radiance Recipe
	refined_radiance_recipe = true
	#.
	#Shadow Steel Recipe Require Max Height
	#Range: -2048 ~ 2048
	refined_radiance_max_height = 319
	#.
	#Shadow Steel Recipe Require Min Height
	#Range: -2048 ~ 2048
	refined_radiance_min_height = -32
	#.
	#Shadow Steel Recipe Require Light Level
	#Range: 0 ~ 15
	refined_radiance_light_level = 15
	#.
	#Shadow Steel Recipe
	shadow_steel_recipe = true
	#.
	#Shadow Steel Recipe Require Min Height
	#Range: -2048 ~ 2048
	shadow_steel_min_height = -10

#.
#Parameters and abilities of Create: Dream n' Desire's kinetic mechanisms
[kinetics]
	#.
	#.
	#multiplier used for calculating exhaustion from speed when a Cog Crank is turned.
	#Range: 0.0 ~ 1.0
	cogCrankHungerMultiplier = 0.009999999776482582

	#.
	#Industrial Fan
	[kinetics.industrialFan]
		#.
		#Maximum distance in blocks Fans can push entities.
		#Range: > 5
		fanPushDistance = 40
		#.
		#Maximum distance in blocks from where Fans can pull entities.
		#Range: > 5
		fanPullDistance = 40
		#.
		#[in Revolutions per Minute]
		#Rotation speed at which the maximum stats of fans are reached.
		#Range: > 64
		fanRotationArgmax = 256

	[kinetics.stressValues]

		#.
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v2]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v2.impact]
				redstone_divider = 0.0
				hydraulic_press = 64.0
				giant_gear = 8.0
				jetpack = 4.0
				industrial_fan = 4.0
				worm_gear = 0.0
				inverse_box = 0.0
				modular_drill = 8.0
				multimeter = 0.0
				brass_gearbox = 0.0

			#.
			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v2.capacity]
				industrial_fan = 16.0
				cog_crank = 8.0
				large_cog_crank = 8.0
				furnace_engine = 256.0
				kinetic_motor = 48.0

#.
#Tweaks for logistical components
[logistics]
	#.
	#.
	#The total amount of stacks a vault can hold per block in size.
	#Range: > 1
	verticalVaultCapacity = 20
	#.
	#The total amount of items that can go through the Burden Chute.
	#Range: 1 ~ 64
	burdenChuteStackSize = 32
	#.
	#The total speed can the item travel through the Burden Chute.
	#Range: 0.0 ~ 20.0
	burdenChuteSpeedMultiplier = 1.5

#.
#Equipment and gadgets added by Create: Dream n' Desire
[equipment]
	#.
	#.
	#The Maximum Amount of Blocks a Excavation Drill can Handle.
	#Range: > -2147483648
	excavationDrillMaximumBlocks = 64
	#.
	#The Maximum Distance at which a Hand Held Nozzle can push/pull your Player.
	#Range: 1.0 ~ 512.0
	handheldNozzleRangePlayer = 8.0
	#.
	#This is dummy text.
	#Range: 1.0 ~ 512.0
	handheldNozzleRange = 16.0
	#.
	#This is dummy text.
	#Range: 0.0 ~ 512.0
	handheldNozzleSpeedLimit = 2.0
	#.
	#This is dummy text.
	#Range: 1 ~ 256
	visorXRAYRange = 16
	#.
	#This is dummy text.
	#Range: 1 ~ 256
	visorCooldownMaxTick = 80
	#.
	#This is dummy text.
	jetpackNeedsBlockBelow = false
	#.
	#This is dummy text.
	#Range: 1.0 ~ 512.0
	jetpackRange = 8.0
	#.
	#This is dummy text.
	#Range: > 1
	jetpackAirMaxTick = 2400
	#.
	#This is dummy text.
	#Range: > 1
	jetpackCooldownMaxTick = 1200
	#.
	#This is dummy text.
	#Range: > 1
	jetpackHeatingMaxTick = 1200
	#.
	#This is dummy text.
	#Range: > 1
	jetpackCoolingMaxTick = 2

